on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/electrical_workflow.yml'
      - '.github/workflows/convert_bottom_position.py'
      - 'Electrical/Design/**'
      - 'docker/electrical-builder/Dockerfile'

jobs:
  build:
    uses: ./.github/workflows/_electrical_build.yml
    secrets: inherit

  deploy-results:
    needs: build
    if: always() && needs.build.result == 'success' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/_deploy_nightly.yml
    with:
      release_name: "Nightly Electrical"
      tag_name: "nightly-electrical"
    secrets: inherit
